
- name: Deploy React Chat Application to Azure App Service
  hosts: localhost
  gather_facts: false

  vars:
    resource_group: my-resource-group
    app_service_plan: my-app-service-plan
    app_name: my-app-service
    git_repo: https://github.com/your-git-repo.git
    location: westus

  tasks:

    - name: Create App Service plan
      azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}" 
        name: "{{ app_service_plan }}"
        is_linux: true
        sku: S1
        number_of_workers: 1
        location: "{{ location }}"

    - name: Create React web app 
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        plan: 
           resource_group: "{{ resource_group }}"
           name: "{{ app_service_plan }}"
        runtimes:
          - name: NODE|14-lts
        location: "{{ location }}"

    - name: Clone Git Repository
      git:
        repo: "{{ git_repo }}"
        dest: /tmp/chat-app

    - name: Deploy React Client
      azure_rm_webapp_deployment:
        resource_group: "{{ resource_group }}"
        name: "{{ app_name }}"
        src_path: /tmp/chat-app/client
        type: zip
        state: present

    - name: Deploy Socket.io Server
      azure_rm_webapp_deployment:
        resource_group: "{{ resource_group }}"
        name: "{{ app_name }}"
        src_path: /tmp/chat-app/server
        type: zip
        state: present

/home/harman/.ssh/authorized_keys